### ISSUE TITLE
max length limit on channels group name

### ISSUE THREAD

**Issue by jbjuin** [hishnash/djangochannelsrestframework#11]
Hi,
I just found out that the obscure channels error message: 

`"Group name must be a valid unicode string containing only ASCII alphanumerics, hyphens, or periods." `

do not mention the fact that group name cannot be longer than 100 characters.

I use UUID as pk and the generated group name (for model observer) exceed that limit:

`1dd94a45-6020-4cc3-8e8a-3b5405a62eb2-handle.instance.change-model-establishment.establishment-pk-b63a92b5-4119-4908-8fcc-28e045a2cbbc`

Any idea on how to solve that ?

**Comment by hishnash** [comment]
@jbjuin thankyou for spotting this

my immediate solution for this would be the hash the `generated` group names and use the hash as the real group name. This should mean group names can be any data type. I will try to get a branch out tomorrow with this fix in place.
