### ISSUE TITLE
[BUG/FEATURE] send_message parameter should be immutable

### ISSUE THREAD

**Issue by cfytrok** [hishnash/djangochannelsrestframework#14]
In ModelObserver.send_message message object passed as mutable. So if you chage it in self.func for one group, other calls of self.func (for other groups) will recieve modified message.
If you don't want to send "type" to ws and call message.pop("type", None) in self.func other groups will not recieve this message.
I think message should be immutable or self.func should recieve copy of message as parametr.

**Comment by hishnash** [comment]
> I think message should be immutable or self.func should recieve copy of message as parametr.

I would assume when using a redis backend this is in effect a copy each time but we should look to make this safe also when using in-memory layer.
