### ISSUE TITLE
DCRF websocket client on npm

### ISSUE THREAD

**Issue by theY4Kman** [hishnash/djangochannelsrestframework#15]
Hello there! Just wanted to mention an npm package I published to provide a websocket client to django-channels-rest-framework: https://github.com/theY4Kman/dcrf-client

It's Promise-based, and supports subscriptions — which can be canceled. The [test/integration/dcrf_client_test directory](https://github.com/theY4Kman/dcrf-client/tree/HEAD@%7B2019-06-01T23:25:53Z%7D/test/integration/dcrf_client_test) contains a Django Channels v2 project as an example for how to setup the Django side of things (with the important thing being the use of `pk` to return a model's ID from a serializer).

If you wanna check it out, it's available [on npm](https://www.npmjs.com/package/dcrf-client)
```bash
npm install dcrf-client
```

**Comment by hishnash** [comment]
sweet I will give this a spin later this week and link from the readme
