### ISSUE TITLE
[SOLVED] In production with gunicorn/daphne/nginx the observer does not seem to work

### ISSUE THREAD

**Issue by egeominotti** [hishnash/djangochannelsrestframework#27]
Using ObserverModelInstanceMixin locally, everything works perfectly, when it is deployed via gunicorn/daphne/nginx, messages are not received.

I wrote a post on stackoverflow about it.

https://stackoverflow.com/questions/63190426/django-channels-rest-framework-dont-return-data-of-subscription-in-production-e

**It has been solved, routing problem with nginx when using daphne + gunicorn thanks the same.**

Thank you

**Comment by moritzxhuber** [comment]
Hi everyone,

I have the exact same problem as @egeominotti described. I use uwsgi for http, daphne for websockets and nginx as a proxy and I start both uwsgi and daphne with supervisord.

Locally everything works fine, I can subscribe to instances and get notified when the model changes. When I deploy everything on AWS however I can still connect to the websocket connection and even retrieve model data or subscribe to instances with the ObserverModelInstanceMixin but when the model changes the new data isn't sent to the client. I checked the nginx setup on the mentioned stackoverflow post, but I still can't make it work.

Here is my nginx config:

upstream websocket-server {
    server localhost:9001;
}

server {
    listen ${LISTEN_PORT};

    server_name *.xxxx.net;

    tcp_nodelay on;

    location /static {
        alias /vol/static;
    }

    location / {
        uwsgi_pass              ${APP_HOST}:${APP_PORT};
        include                 /etc/nginx/uwsgi_params;
        client_max_body_size    50M;
    }

    location /ws/ {
        proxy_pass              http://websocket-server;
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "Upgrade";
        proxy_redirect          off;
        proxy_buffering         off;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Host $server_name;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_read_timeout      18000s;
        client_max_body_size    5M;
    }
}


@egeominotti could you please tell me what exactly was the problem and what helped you solve it with the nginx config or do you guys have any other idea what I could try or what could be wrong?

If you need more information please let me know. I'm stuck for days and help would be really appreciated.

Thank you,
Moritz
