### ISSUE TITLE
[BUG] ObserverModelInstanceMixin seems to not be working across threads/processes

### ISSUE THREAD

**Issue by gegenschall** [hishnash/djangochannelsrestframework#28]
**Describe the bug**
I have one simple Consumer + Multiplexer as follows:
```python
class TaskStatusConsumer(ObserverModelInstanceMixin, GenericAsyncAPIConsumer):
    queryset = TaskStatus.objects.all()
    serializer_class = TaskStatusSerializer
    permission_classes = (permissions.AllowAny,)


class StatusDemultiplexerAsyncJson(AsyncJsonWebsocketDemultiplexer):
    applications = {
        'task-status': TaskStatusConsumer
    }
```

I subscribe to events using `dcrf-client` on the JavaScript side of things. I see that the WebSocket connection successfully subscribes to a newly created model instance using `subscribe_instance`. 

I have a view similar to this:

```python
class TaskStatusViewSet(viewsets.ModelViewSet):
    queryset = TaskStatus.objects.all()
    serializer_class = serializers.TaskStatusSerializer

    @action(methods=['post'], detail=True)
    def some_action(self, request, pk=None):
        task = TaskStatus.objects.get(pk=pk)
        task.some_attr = 'some-value'
        task.save()
```

When sending a request to that view I do see an update message for the `task.save()` call being sent down on the WebSocket.

Yet any subsequent requests are not being being sent over the WebSocket connection. Somehow the model observer "forgets" about the model instance after the initial request is made. 

Am I using the Observer wrong?

**Comment by gegenschall** [comment]
I'm having a hard time debugging this issue. It seems that for each request a new UUID is generated by the ModelObserver sucht that subsequent requests can never it the same channel, i.e. updates only work within one thread. As soon as the thread or async function is destroyed no updates can be sent anymore. Is this correct?

**Comment by hishnash** [comment]
What Channel layer are you using? https://channels.readthedocs.io/en/latest/topics/channel_layers.html#:~:text=Channel%20layers%20are%20configured%20via,on%20the%20consumer%20as%20self.

The channel layer is used to handle the passing of messages between proses.

**Comment by gegenschall** [comment]
Thanks for your reply! 

I'm using the Redis Channel Layer, relevant config:
```python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL]
        },
    },
}
```

As far as I can tell, the channel group name is not stable in my case. I'm not entirely sure but as far as I understand the code, for each instantiated Consumer a new `_uuid`/`id` property is generated thus each thread/process generates its own groups that are not visible to other Consumer.

**Comment by hishnash** [comment]
oh! your right!!! that is embracing ;) I will try to get a quick turnaround on this one.

**Comment by gegenschall** [comment]
Oh that's awesome. Will check out your changes hopefully today and report back. Looks great so far!
