### ISSUE TITLE
Error While Using Custom Actions.

### ISSUE THREAD

**Issue by saurav1916** [hishnash/djangochannelsrestframework#31]
{
  "errors": ["Method \"method name\" not allowed."],
  "data": null,
  "action": "method name",
  "response_status": 405,
  "request_id": 5
}
everytime i got this thing while using custom actions.

**Comment by hishnash** [comment]
can you share what message you are sending over the websocket form the client and your consumer code?

**Comment by saurav1916** [comment]
{
"action" : "hello" ,
"request_id" : 3
}




class ListOfUsers(AsyncAPIConsumer):

    @action()
    async def hello(self,request):
        print("hello")
        user=User.objects.all().values()
        obj=userlist(user,many=True)
        return Response({"List":obj.data})

**Comment by hishnash** [comment]
Strange... (what version of python are you running?, not that it should matter)

Would you be able to add:

```python
def __init__(*args, **kwargs):
    super().__init__(*args, **kwargs)
    print(self.available_actions)
```

what does this print?

**Comment by saurav1916** [comment]
it shows websocket DISCONNECT

**Comment by saurav1916** [comment]
GOT THIS : TypeError: hello() got an unexpected keyword argument 'request_id'
when i send THIS->{
"action" : "hello" ,
"request_id" : 3
}

GOT This:KeyError: 'request_id'
when i send this -> {
"action" : "hello" ,
"request_id" : 3
}

**Comment by hishnash** [comment]
the `KeyError: 'request_id'` is expected since your method def is `async def hello(self,request):` should be `async def hello(self, **kwargs):`  (the body of your ws message is unpacked as kwargs into the method).

Also I see in your `hello` method you are hitting the db directly:

* If you do not need the `hello` action to be async remove the `async` keyword and you will have a sync method that can call the db. 
* If you need the method to be async then you should wrap all db operations in `await database_sync_to_async` see https://channels.readthedocs.io/en/latest/topics/databases.html

This looks like an addition to an existing case https://github.com/hishnash/djangochannelsrestframework/issues/26 for improving the error messages when the `kwargs` of the `action` do not line up with the values sent in the message

**Comment by saurav1916** [comment]
When i removed async i got ->  
hello
Exception inside application: The response content must be rendered before it can be iterated over.

**Comment by hishnash** [comment]
oh yer I did not look at `Response({"List":obj.data})` what is this? 

normally actions will return `return {'response with': 'some message'}, 200` 

so maybe you need to do `return Response({"List":obj.data}).data, 200`

**Comment by saurav1916** [comment]
After doing return { "List" : obj.data }

Got this -> valueError: not enough values to unpack (expected 2, got 1)

**Comment by saurav1916** [comment]
class ListOfUsers(AsyncAPIConsumer):

    @action()
    async def hello(self,**kwargs):
        user = await database_sync_to_async(self.check)()
        obj=userlist(user,many=True)
        return {"List":obj.data},200

    def check(self):
        return User.objects.all()

why this throuing an error below-->>

Exception inside application: You cannot call this from an async context - use a thread or sync_to_async.

**Comment by hishnash** [comment]
is `userlist` doing anything that might result in a db query, maybe you need to `select_related`/`prefetch_related` in your `check` query?  or wrap `userlist` in `database_sync_to_async`.

**Comment by saurav1916** [comment]
class ListOfUsers(AsyncAPIConsumer):

    @action()
    async def hello(self,**kwargs):
        user = await database_sync_to_async(self.check)()
        return {"List":user},200

    def check(self):
        user=userlist(User.objects.all(),many=True)
        return user.data


I did this and getting the expected data from Database but whenever i make  changes in Database the corresponding is not getting updated in the data i got before. 

I have to again send the { "action":"hello","request_id" : 1 } to see the changes.

Why is this ? Since our method is async .

**Comment by hishnash** [comment]
The method being async does not mean it auto updates, the async is purly there if you need to do `async` work (eg make another network request).

if you want to subscribe to yoru user list i suggest you look at this blog post: https://lostmoa.com/blog/BuildingARealtimeSocialNetworkUsingDjangoChannels/

```python
class ListOfUsersConsumer(...):
    
    @model_observer(models.User)
    async def user_change_handler(self, message, observer=None, **kwargs):
        # called when a subscribed item changes
        await self.send_json(message)

    @action()
    async def subscribe_to_userlist(self, **kwargs):
        await self.user_change_handler.subscribe(
            hashtag=hashtag
        )
        return {}, 201

    @action()
    async def unsubscribe_from_userlist(self, **kwargs):
        await self.user_change_handler.unsubscribe(
            hashtag=hashtag
        )
        return {}, 204
```

This will setup so when you send 
```json
{
    "action": "subscribe_to_userlist", "request_id": 42
}
```

Then when there is a change (to any user) you will get a message sent.

**Comment by saurav1916** [comment]
CoooL.
So this is only way to make our applications realtime like (Chat Application) and other things?

**Comment by hishnash** [comment]
For chat applications you are better of using regular `group subscriptions` https://channels.readthedocs.io/en/latest/tutorial/part_3.html

here you can use the `@action` based methods to replace the `receive`

```python
    
    @action()
    async def send_message(self, body, **kwargs):
  
        message = text_data_json['message']

        # Send message to room group
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'chat_message',
                'message': body
            }
        )
```

then to send a msg

```json
{
   "action": "send_message", "request_id": 42,
   "body": {"test": "message"}
}
```

You could also use an `@action` based method for subscription/unsubscribign to a group rather than doing it in the `connect` method but that depends on your use case.
