### ISSUE TITLE
Detail Documentation

### ISSUE THREAD

**Issue by Fahad-Md-Kamal** [hishnash/djangochannelsrestframework#33]
Hi, Hishnash.

I believe your project would be very much promising for the beginners like me if you had provided a little bit more detailed documentation.

Actually I'm trying to create a chat application with Django Channels which is very confusing. But yours seems would ease the burdain if there is a detail documentation. 

N.B: I'm doing my Final Year project with Django Rest Framework which is why may be your short Documentation is very confusing for me to apply in my project. 

Please, help me with any resources to implement your project in my solution.

**Comment by hishnash** [comment]
Hi @Fahad-Md-Kamal 

sorry about the documentation, this is still a very much work in progress part of the project.

> Actually I'm trying to create a chat application with Django Channels

For this application are you intending on saving the chat to the database?

**Comment by Fahad-Md-Kamal** [comment]
Yes, Hishnash... I want to save the chat messages to my database and retrieve those.

**Comment by zOthix** [comment]
Any update?

**Comment by lautarodapin** [comment]
I'm not in the computer, I will answer with more detail later.
You should use models for messages and rooms
Use actions for joining, saving room code and creating the message.
The  you should subscribe to messages in current room.
https://github.com/lautarodapin/noticias-vm/blob/main/chat/consumers.py check this that I made myself

**Comment by the-wc** [comment]
Any word on the update on this? The documentation on "Subscribing to a filtered list of models" is puzzling.
