### ISSUE TITLE
The ObserverModelInstanceMixin is not found in the djangochannelsrestframework.mixins.

### ISSUE THREAD

**Issue by rikesh1212** [hishnash/djangochannelsrestframework#39]
**Describe the bug**
from djangochannelsrestframework.mixins import ObserverModelInstanceMixin

ObserverModelInstanceMixin is not found. Have you removed it from the package?

**Comment by hishnash** [comment]
Sorry there is a typo in the blog article. 

This should work:
```python
from djangochannelsrestframework.observer.generics import ObserverModelInstanceMixin
```
