### ISSUE TITLE
Integration with React

### ISSUE THREAD

**Issue by DUMBALINYOLO** [hishnash/djangochannelsrestframework#51]
Can this Library be integrated with React Js or one needs to use drf-client only???

**Comment by hishnash** [comment]
You can this library directly with the raw JS WS api that is in the browser: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket.

**Comment by DUMBALINYOLO** [comment]
Thanks man this is great library you came up with. I shall testdrive it over weekend and see if I can rely upon it in my projects
