### ISSUE TITLE
[BUG] `ATOMIC_REQUESTS` is checked for in the wrong place.

### ISSUE THREAD

**Issue by jhillacre** [hishnash/djangochannelsrestframework#64]
**Describe the bug**
djangochannelsrestframework's (DCRF) `action` decorator looks in Django's settings for `ATOMIC_REQUESTS`. Since at least Django 1.8, `ATOMIC_REQUESTS` has been a setting specific to a connection defined in the `DATABASE` setting. When `ATOMIC_REQUESTS` is setup as described in Django documentation, DCRF's `action` decorator does not wrap sync actions in an `atomic` block, or throw errors on async actions that cannot be wrapped.

See:
* https://docs.djangoproject.com/en/1.8/ref/settings/#atomic-requests
* https://docs.djangoproject.com/en/3.1/ref/settings/#atomic-requests

**To Reproduce**
1. Setup django databases. (In this case, setup as in [cookiecutter-django](https://github.com/pydanny/cookiecutter-django/blob/a18ccd35238745c588281b1436807c65ccd3c5d6/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L43-L50)).
    ```python
    # DATABASES
    # ------------------------------------------------------------------------------
    # https://docs.djangoproject.com/en/dev/ref/settings/#databases
    DATABASES = {"default": env.db("DATABASE_URL", default="postgres:///project")}
    DATABASES["default"]["ATOMIC_REQUESTS"] = True
    ```
2. Run a custom async action:
   ```python
   @action
   async def change_password(self, current_password="", new_password="", confirm_password="", **kwargs):
       ...
   ```

**Expected behavior**
The custom async action, wrapped using `@action` should throw the exception from this line:
https://github.com/hishnash/djangochannelsrestframework/blob/master/djangochannelsrestframework/decorators.py#L54

DCRF's `action` decorator should take a `using` kwarg, similar to `atomic`'s `using` kwarg, which is used to check if a specific db connection wants to be wrapped in `atomic` blocks. Barring support for the `using` kwarg, the default connection should at least be checked for `ATOMIC_REQUESTS`.

**Comment by hishnash** [comment]
Good catch.

I will look into this today. 

Likely i will move the check for reading the settings of atomic to after the async method test (so that the error is only thrown if you expisilty set `@action(atomic=True)` on an async method. Also pulling the `atomic` value from the default connection db makes sense.  

I will look into adding the `using` kwarg but i feel that is a feature of its own as it will come with some other complexities around the DB connection that is created for the sync action.

**Comment by jhillacre** [comment]
While not directly related, I needed to set atomic=False on `ObserverModelInstanceMixin` actions in order to get my server to run with `ATOMIC_REQUESTS=True`.

https://github.com/arrai-innovations/djangochannelsrestframework/commit/3c654eb2680bd7321777c084ba31547fda46bc92

**Comment by hishnash** [comment]
Yer i spotted that, if I move  https://github.com/hishnash/djangochannelsrestframework/blob/master/djangochannelsrestframework/decorators.py#L45 to after the async method check then that issue will go-away.

**Comment by jhillacre** [comment]
Right, I see that now. I was not understanding.

**Comment by jhillacre** [comment]
tyvm 👍
