### ISSUE TITLE
[BUG] Subscribing to model

### ISSUE THREAD

**Issue by AUitto** [hishnash/djangochannelsrestframework#82]
**Describe the bug**
I'm trying to subscribe for model changes with no luck. I'm following exactly the guide on https://djangochannelsrestframework.readthedocs.io/en/latest/observer/base_observer.html.

**To Reproduce**
1. Follow guide on https://djangochannelsrestframework.readthedocs.io/en/latest/observer/base_observer.html
2. Create comments as user 1 and user 2.
3. Nothing is returned from the server.

**Expected behavior**
1. Changes made in model is returned from the server.

 - OS: Debian
 - Version 10.9 (WSL)

**Additional context**

I have following consumer:

```
# consumers.py

from djangochannelsrestframework.generics import GenericAsyncAPIConsumer
from djangochannelsrestframework.observer import model_observer
from djangochannelsrestframework.decorators import action

from .serializers import UserSerializer, CommentSerializer
from .models import User, Comment

class MyConsumer(GenericAsyncAPIConsumer):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    @model_observer(Comment)
    async def comment_activity(self, message: CommentSerializer, observer=None, **kwargs):
        print("Model observer 1")
        await self.send_json(message.data)
        print("Model observer 1")

    @comment_activity.serializer
    def comment_activity(self, instance: Comment, action, **kwargs) -> CommentSerializer:
        print("Serializer 1")
        '''This will return the comment serializer'''
        return CommentSerializer(instance)
        print("Serializer 2")

    @action()
    async def subscribe_to_comment_activity(self, **kwargs):
        print("Subscribe 1")
        await self.comment_activity.subscribe()
        print("Subscribe 2")
```

And I have a template index.html:
```
<script>
    const ws = new WebSocket("ws://localhost:8000/ws/my-consumer/")

    ws.onopen = function(){
        ws.send(JSON.stringify({
            action: "subscribe_to_comment_activity",
            request_id: new Date().getTime(),
        }))
    }
    ws.onmessage = function(e){
        console.log(e)
    }
</script>
```

When I refresh the browser, I can see that the browser sends the _subscribe_to_comment_activity_, but nothing is returned back, even when I create the comments from shell.

The server log prints following:
```
System check identified no issues (0 silenced).
June 06, 2021 - 10:41:31
Django version 3.2.3, using settings 'websocket.settings'
Starting ASGI/Channels version 3.0.3 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
HTTP GET / 200 [0.01, 127.0.0.1:64881]
WebSocket HANDSHAKING /ws/my-consumer/ [127.0.0.1:64882]
WebSocket CONNECT /ws/my-consumer/ [127.0.0.1:64882]
Subscribe 1
Subscribe 2
```
The above would indicate that it probably did not reach the model observer or the serializer.

I'm wondering if the imported _GenericAsyncAPIConsumer_ is correct, as it indeed is different from the documentation, as it could not be found from _djangochannelsrestframework.consumers_. Any ideas?

**Comment by hishnash** [comment]
Sorry for the very slow response :(

when creating models (in the shell etc) you need to ensure the file that contains `MyConsumer` has been imported (otherwise the on change hooks it provides are not picked up by your shell session). 

This is also true for other situations such as regular rest endpoints.

**Comment by ATeryohin** [comment]
How can i fix this? Only import **MyConsumer** in **__init__.py** inside other apps where create object? Or anything else?

**Comment by W0rtX** [comment]
@ATeryohin did you manage to get this working?

**Comment by ATeryohin** [comment]
Yeah, i was add import my consumer to apps.py into my app.

Example:
class TestAppConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'testapp'

    def ready(self):
        from OtherApp import consumers

**Comment by W0rtX** [comment]
> Yeah, i was add import my consumer to apps.py into my app.
> 
> Example:
> 
> ```
> class TestAppConfig(AppConfig):
>     default_auto_field = 'django.db.models.BigAutoField'
>     name = 'testapp'
> 
>     def ready(self):
>         from OtherApp import consumers
> ```

You are save my next weekend!
Thank you!
