### ISSUE TITLE
An open stream object is being garbage collected; call "stream.close()[BUG]

### ISSUE THREAD

**Issue by ericel** [hishnash/djangochannelsrestframework#89]
**Describe the bug**
I am getting this bug when using the 

>from marketplace.consumers import ListConsumer
> TestChannel.objects.create(text="user21 creates a new comment", user=user_1)
> TestChannel object (7)
> An open stream object is being garbage collected; call "stream.close()" explicitly.
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
>     obj.save(force_insert=True, using=self.db)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
>     self.save_base(using=using, force_insert=force_insert,
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/db/models/base.py", line 774, in save_base
>     post_save.send(
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
>     return [
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
>     (receiver, receiver(signal=self, sender=sender, **named))
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/djangochannelsrestframework/observer/model_observer.py", line 108, in post_save_receiver
>     self.database_event(instance, Action.CREATE)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/djangochannelsrestframework/observer/model_observer.py", line 127, in database_event
>     connection.on_commit(partial(self.post_change_receiver, instance, action))
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/django/db/backends/base/base.py", line 645, in on_commit
>     func()
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/djangochannelsrestframework/observer/model_observer.py", line 155, in post_change_receiver
>     self.send_messages(
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/djangochannelsrestframework/observer/model_observer.py", line 173, in send_messages
>     async_to_sync(channel_layer.group_send)(group_name, message_to_send)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/asgiref/sync.py", line 222, in __call__
>     return call_result.result()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
>     raise self._exception
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/asgiref/sync.py", line 287, in main_wrap
>     result = await self.awaitable(*args, **kwargs)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/channels_redis/core.py", line 684, in group_send
>     ) = self._map_channel_keys_to_connection(channel_names, message)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/channels_redis/core.py", line 819, in _map_channel_keys_to_connection
>     channel_key_to_message[key] = self.serialize(value)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/channels_redis/core.py", line 839, in serialize
>     value = msgpack.packb(message, use_bin_type=True)
>   File "/Users/ericel123/Documents/dev/django/lib/python3.8/site-packages/msgpack/__init__.py", line 35, in packb
>     return Packer(**kwargs).pack(o)
>   File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
>   File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
>   File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
>   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
>   File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
> TypeError: can not serialize 'TestChannelSerializer' object

**To Reproduce**

```
class ListConsumer(ListModelMixin, GenericAsyncAPIConsumer, ): 
    print('got here')
    queryset = TestChannel.objects.none()
    serializer_class = TestChannelSerializer
    permission_classes = [permissions.AllowAny]
    async def accept(self, **kwargs):
        await super().accept(** kwargs)
        await self.model_change.subscribe()

    @model_observer(TestChannel)
    async def model_change(self, message, action=None, **kwargs):
        await self.send_json(message)

    @model_change.serializer
    def model_serialize(self, instance, action, **kwargs):
        return TestChannelSerializer(instance).data

    def get_queryset(self, *args, **kwargs):
        #user = self.scope['user']
        return TestChannel.objects.all()

```

**Expected behavior**
I should expect the console update on the new comment created. But the console doesn't log updates.
**LOG**
If applicable, add a log to help explain your problem.
<img width="446" alt="Screen Shot 2021-08-16 at 9 05 33 PM" src="https://user-images.githubusercontent.com/16863721/129561013-063e7d94-ec24-4b80-ad0b-94114fe0df2b.png">

 - OS: [MacOS]
Can this be a Python version problem? I am using 3.8.0

**Comment by ericel** [comment]
This is a Python version problem. Python 3.8.0 is the culprit here.

**Comment by hishnash** [comment]
@ericel this is interesting thankyou for confirming.
