### ISSUE TITLE
[BUG] Support for Python 3.6  

### ISSUE THREAD

**Issue by ravi45722** [hishnash/djangochannelsrestframework#97]
**Describe the bug**
in generics.py  line 1 has import of
from typing import Any, Dict, Type, Optional, List, OrderedDict, Union

OrderedDict is having support from only 3.7 later

**To Reproduce**
1. Install 3.6
2. Write an API using GenericAsyncAPIConsumer

**Expected behavior**
No error should come

**Comment by johnthagen** [comment]
The CI for this project only tests against Python 3.8 and 3.9:

https://github.com/hishnash/djangochannelsrestframework/blob/ae55bace7d7c60b25c8da08c4758c2fbf861697e/.github/workflows/tests.yaml#L17-L19

It would be good to add `python_requires` to `setup.py` to be explicit about what versions are supported and so `pip` can install older versions when older versions of Python are dropped.

Also, for Python 3.6 in particular, it is going end of life in 1 month, so it may not be something the maintainer wants to continue to support: https://endoflife.date/python
